name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-checks:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repo
         uses: actions/checkout@v5

       - name: Install uv
         uses: astral-sh/setup-uv@v7.6.0
         with:
          enable-cache: true

       - name: Set up Python
         run: uv python install

       - name: Install Python project
         run: uv sync --locked --all-extras --dev

       - name: Check Python linting and formatting with Ruff
         run: |
           uv run ruff check
           uv run ruff format --check

       - name: Check Python docstring coverage
         run: uv run docstr-coverage ./**/*.py --fail-under 20 --verbose=2 --skip-file-doc --skip-init

       - name: Check code complexity with Complexipy
         uses: guzmanlopez/complexipy-action@feature/update-to-complexipy-v5
         with:
           paths: .
           max_complexity_allowed: 20
           output_json: true
        
       - name: Run tests with pytest
         run: uv run pytest

  rust-checks:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repo
         uses: actions/checkout@v5

       - name: Set up Rust
         uses: dtolnay/rust-toolchain@nightly
         with:
           components: rustfmt, clippy

       - name: Cache Rust dependencies
         uses: Swatinem/rust-cache@v2

       - name: Check Rust formatting with rustfmt
         run: cargo fmt --all -- --check

       - name: Check Rust code with Clippy
         run: cargo clippy --all-features -- -D warnings

