name: Style checks

on: [ push, pull_request ]
jobs:
  style-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7.6.0
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install Python project
        run: uv sync --locked --all-extras --dev

      - name: Check Python linting with Ruff
        run: uv run ruff check

      - name: Check format with Ruff
        run: uv run ruff format --check

      - name: Check Python docstring coverage
        run: uv run docstr-coverage ./**/*.py --fail-under 20 --verbose=2 --skip-file-doc --skip-init
      
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check Rust formatting with rustfmt
        run: cargo fmt --all -- --check

      - name: Check Rust code with Clippy
        run: cargo clippy --all-features -- -D warnings
